<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Msg</string>
    <key>scopeName</key>
    <string>source.msg</string>

    <key>fileTypes</key>
    <array>
        <string>action</string>
        <string>msg</string>
        <string>srv</string>
    </array>

    <key>patterns</key>
    <array>
    </array>
</dict>
</plist>
